@startuml
Class Application {
    +main(String[] args)
    +start()
}
Class ToDoList {
    -ObservableList<Item> items
'3 character title
    +addItem()
    +editItem()
    +getItemCount()
    +clearList()
}
Class Item {
    -String description
    -String dueDate
    -Boolean completed

    +editDescription()
    +editDueDate()
    +validateDescription()
    +validateDueDate()
    +markComplete()
}
Class DataHandler {
    -String buffer
    +ToDoList data
    +save()
    +load()
    -toParse()
    -fromParse()
}
Class ApplicationController {
    'fxml controller
}
Application -- ApplicationController
ApplicationController --o DataHandler
DataHandler --o ToDoList
ToDoList --o Item
@enduml